name: Linux tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'ubuntu'
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install System Packages
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -qq pyqt5-dev-tools libxcb-xinerama0 xterm --fix-missing
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: true
           channels: conda-forge
           channel-priority: strict
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install package dependencies
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest --cov-report xml --cov=spyder_env_manager -x -vv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
